### ISSUE TITLE
Mining Granite Iron Ore drops Stone Iron Ore

### ISSUE THREAD

**Issue by XViGames0** [Better-than-Adventure/bta-issues#264]
Mining Granite Iron Ore with an adequate pickaxe drops the Stone Iron Ore block.

Steps to reproduce:
-Craft a Stone Pickaxe or better
-Find Granite Iron Ore
-Mine the ore

Expected Behavior:
Mining the ore would drop the Granite Iron Ore block.

Version 1.7.6.2_02

**Comment by jonkadelic** [comment]
This is a deliberate design choice to prevent inventory bloat. The non-stone versions of ores can be obtained via piston crushing or gold pickaxe silk touch.

In 1.7.7.0, these will be replaced by raw ores.
