### ISSUE TITLE
Add an optional texture pack for the modern JAPPA textures

### ISSUE THREAD

**Issue by Aproxia-dev** [Better-than-Adventure/bta-issues#272]
**Is your feature request related to a problem? Please describe.**
I'm way too used to the JAPPA textures from 1.14, and I kind of miss them...

**Describe the solution you'd like**
Do the exact same thing that Mojang did, except the other way around - Keep the default textures, and make the JAPPA textures an optional, included texture pack.

**Describe alternatives you've considered**
Making it myself and making a public download, I guess... :p

**Comment by jonkadelic** [comment]
This really isn't our responsibility. You can find a Jappa-style texture pack made by the community available on the Discord server.
