### ISSUE TITLE
Higher CPU usage in latest version

### ISSUE THREAD

**Issue by TheFortunattor** [Better-than-Adventure/bta-issues#276]
**Higher CPU usage on version 1.7.7.0_02**
I didn't do super in-depth testing but I've noticed significantly higher CPU usage on versions after 1.7.6.X

**To Reproduce**
1. Boot up a 1.7.6.X instance and create a world
2. Set Performance to "power save" as no VSync exists in this version and measure CPU performance after waiting a few seconds upon entering the world. It hovers around 3~5% with low usage on all cores
3. Boot a 1.7.7.X instance and load up that same world for consistency, setting performance to "power save" as well. In this instance, CPU usage is significantly higher as there's always at least 1 CPU core pegged at 100%. 
3a. Just to try it, if I turn on VSync in this version, there will now be two CPU cores pegged at 100% or one at 100% and two more with fluctuating usage. 

-- Please note that while I transferred a world from the old version to the new one, I've encountered this upon creating a new world in the new instance as well. I was just using the same world between versions for consistency.

**Expected behavior**
Lower CPU utilization.

**Screenshots**
Version 1.7.6_01:
![bta1 7 6](https://github.com/Better-than-Adventure/bta-issues/assets/50719030/2fbfa1b0-6eca-4036-80a8-f1571cfcb03a)

Version 1.7.7.0_02 (Power save):
![bta1 7 7](https://github.com/Better-than-Adventure/bta-issues/assets/50719030/91c1e46e-84cb-4931-bfdf-569caa74c662)

Version 1.7.7.0_02 (VSync):
![bta1 7 70-2](https://github.com/Better-than-Adventure/bta-issues/assets/50719030/5b4b8317-3516-4703-ac19-2d24a9589078)

**Version info (please complete the following information):**
 - Version 1.7.7.0_02

**Additional context**
This was tested on Arch Linux using the flatpak version on Prism Launcher, a ZIP instance for version 1.7.6_01 taken from bta-download-repo (Files-MultiMC-1.7.6_01.zip) and a fresh managed instance using the auto updater 2.0. Both version were run using the included java 8 of the flatpak prism launcher but I also tested 1.7.7.0_02 using java 17 from Eclipse adoptium and got the same result. 

I have a Ryzen 5 5600, 16GB of RAM and a RTX 3070 with 535.104.05 of the proprietary NVIDIA drivers. 

Also, just to be clear, performance is not bad at all just that CPU usage seems a bit high in my opinion compared to previous versions. If you need anything else, please let me know. 

**Thank you for making such an awesome mod!**

**Comment by LukasEins** [comment]
having a very similar issue, my CPU gets very hot when im loaded into a world for no apparent reason, no setting has any impact, performance is totally fine but my 5800x3d gets hotter playing this pack than it does playing cyberpunk on ultra settings, doesnt happen on any other modpack or version either, using Windows 10 latest AMD drivers with RX 6800

**Comment by bestsoft100** [comment]
There was an issue in 1.7.7.0 where the chunk saving thread would run all the time, which caused high CPU usage. That has been fixed
