### ISSUE TITLE
Wrong z-index of buttons in options

### ISSUE THREAD

**Issue by Michael-Soyka** [Better-than-Adventure/bta-issues#278]
**Describe the bug**
When scrolling down the list, the buttons (Open Screenshots Folder & Open Worlds Folder) are on the top layer.

**To Reproduce**
1. Run the bta1.7.7.0_02
2. Go to Options
3. Scroll down

**Expected behavior**
The buttons are on the lower layer and hidden by the upper one.

**Screenshots**
![damn_buttons](https://github.com/Better-than-Adventure/bta-issues/assets/45078459/22e3e862-6bb1-47f0-9d4c-484121c5c37b)

**Version info**
 - Version 1.7.7.0_02

**Additional context**
- Prism Launcher 7.2
- BTA 1.7.7.0_02
- Java version "17.0.8" 2023-07-18 LTS
- Windows 11 Pro Insider Preview (10.0.23506)

**Comment by bestsoft100** [comment]
Fixed
