### ISSUE TITLE
Snow layers form under glass blocks.

### ISSUE THREAD

**Issue by TurboFunder** [Better-than-Adventure/bta-issues#286]
So, I searched and I don't believe anyone has reported this? In my single player world, when it snows during winter I find snow layers forming in my house. This is exclusively under glass blocks. I would do further testing, however unable to set the season makes it difficult. If you take a look at these screenshots, you'll see an example of what I see. I noticed this is only happening with glass blocks that only air above them. If a block is over the glass block, even with air in-between, the snow does not form. The glass blocks with exclusively air above them have snow layers form below them.

I believe you just need glass with only air above it with snow to reproduce.

Screenshots
![2023-09-11_23 50 07](https://github.com/Better-than-Adventure/bta-issues/assets/62969085/3cc007fe-ad9b-4e64-8efc-1494db808fa0)
![2023-09-11_23 50 14](https://github.com/Better-than-Adventure/bta-issues/assets/62969085/76a88b32-6dcf-42e3-9a85-f98ba8e3e251)
![2023-09-11_23 50 20](https://github.com/Better-than-Adventure/bta-issues/assets/62969085/706e719f-9224-4e88-88c8-fb2d899a386a)
![2023-09-11_23 50 37](https://github.com/Better-than-Adventure/bta-issues/assets/62969085/d232af5e-d694-4e94-abb8-512e3440be98)
![2023-09-11_23 50 53](https://github.com/Better-than-Adventure/bta-issues/assets/62969085/304d458f-6bf5-4882-9204-0ad32f60941b)

If this is still open when the new update is pushed with seasonal commands, I will do further testing.

Versions:
Java: standard java 17.0.1 release by eclipse adoptium
BTA: 1.7.7.0_02
No added mods, I am running a texture pack.

**Comment by chowder3907** [comment]
If you want to test further, you can use the time set command in creative to change the season. For instance, `/time set 576000` will set it to the middle of the first winter

**Comment by xtosutosu** [comment]
I believe it is a known issue. AFAIK it will be fixed in 7.1.

**Comment by jonkadelic** [comment]
Fixed in 7.1.
