### ISSUE TITLE
Open folder buttons overlapping Done button in General tab of settings

### ISSUE THREAD

**Issue by iwalfy** [Better-than-Adventure/bta-issues#288]
**Describe the bug**
Open world folder and Open screenshots folder buttons overlapping Done button in General tab of Settings instead of being inside container.

**To Reproduce**
1. Open game
2. Go to Settings
3. Open General tab
4. Scroll down

**Expected behavior**
Buttons stays inside container and not overlapping Done button

**Screenshots**

**Version info (please complete the following information):**
 - Version 1.7.7.0_02

**Additional context**
 - macOS Ventura 13.4
 - 2560x1600 (scaled 1680x1050)

https://github.com/Better-than-Adventure/bta-issues/assets/99194003/efa0402f-59b8-48ee-b06c-3d46f93f2eb9

**Comment by camping6464** [comment]
Yeah, it's pretty infuriating to see a layering oversight. Hope this gets patched up in a next update, major or minor.

**Comment by jonkadelic** [comment]
Fixed in 7.1.
