### ISSUE TITLE
Sticky movement keys when opening containers

### ISSUE THREAD

**Issue by miraficus** [Better-than-Adventure/bta-issues#291]
**Describe the bug**
If you press any movement key at the same time as opening a chest for example you will keep walking in that direction until you click the key again. 

**To Reproduce**
1. Place a chest, Workbench or furnace...
2. Click on it with right mouse button and "S" key at the same time.
3. Now you are moving backwards until you exit the GUI and press "S" key again.

**Expected behavior**
It should open chest and stop any movement.

**Version info**
 - Version 1.7.7.0_02

**Additional context**
BTA though Prism Launcher on Linux Mint

**Comment by bestsoft100** [comment]
Fixed
