### ISSUE TITLE
Some things don't pick up

### ISSUE THREAD

**Issue by mezerable** [Better-than-Adventure/bta-issues#294]
When breaking a particular block there is a chance that some of the dropped items will not be picked up

1. Break some blocks
2. Try to pick up them
3. ?????
4. Some of them don't!

Was expecting to get blocks in the same amount I broke them in

![2023-12-18_18 08 24](https://github.com/Better-than-Adventure/bta-issues/assets/130295959/b53bf494-132e-458b-9e12-a69574aa005a)

 - Version [e.g. 7.1 Prerelease 1

**Comment by mezerable** [comment]
ah, yes, trommel is useless now

**Comment by UselessBullets** [comment]
there is a jar mod patch for this issue from one of the devs, so yes it is known and it will be fixed. as for the trommel as long as it directly deposits its items into a chest you shouldn't ever lose any

**Comment by bestsoft100** [comment]
Fixed in 7.1pre1a
