### ISSUE TITLE
Why does this keep occuring whenever I try to join a BTA server.

### ISSUE THREAD

**Issue by MasterHamOff** [Better-than-Adventure/bta-issues#320]
**Describe the bug**

1. It seems that for whatever reason whenever I try to join a server it brings me to the title screen and gives me a crash report.

**To Reproduce**
First, launch the instance.
Then, go to the multiplayer tab and tap on the server.
Finally, when done it'll send you back to the title screen with a crash report.

**Expected behavior**
I expected to join the server; however, whenever I try to it gives me the same error even when I deactivate mods. It seems that Minecraft is conflicting with something.

This is a video that shows how it occurs:
(https://github.com/Better-than-Adventure/bta-issues/assets/171278800/1003194e-cdb6-48b4-a13d-078cebd398f5)

**Version info (please complete the following information):**
Version: B.T.A 7.1

**Additional context**
I looked through the server logs and it shows me joining then quickly leaving.

**Crash Logs**
Minecraft ran into an unexpected problem!

To prevent more problems, the current game has quit, but you can try to keep playing.

If you wish to report this, please copy this entire text and post it on the forum thread at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/3106066-better-than-adventure-for-beta-1-7-3-timely, or join the Discord server at https://betterthanadventure.net/discord and post it in #bug-reports.

Generated 5/30/24, 1:48 PM

Minecraft: Better than Adventure! 7.1
OS: Windows 11 (amd64) version 10.0
Java: 18.0.1.1, Oracle Corporation
VM: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
LWJGL: 2.9.4-babric.1
OpenGL: Intel(R) UHD Graphics version 4.6.0 - Build 27.20.100.9365, Intel

java.lang.NullPointerException: Cannot invoke "java.net.Socket.getInetAddress()" because "socket" is null
    at b100.minimap.mc.impl.MinecraftHelperImpl.getServerName(MinecraftHelperImpl.java:186)
    at b100.minimap.data.WorldDataManager.getWorldData(WorldDataManager.java:25)
    at b100.minimap.Minimap.onWorldChange(Minimap.java:261)
    at b100.minimap.Minimap.onRenderGui(Minimap.java:126)
    at b100.minimap.asm.MinimapASM.onRender(MinimapASM.java:15)
    at net.minecraft.client.render.WorldRenderer.updateCameraAndRender(WorldRenderer.java:591)
    at net.minecraft.client.Minecraft.run(Minecraft.java:842)
    at java.base/java.lang.Thread.run(Thread.java:833)

The Instance Folder Lay Within
https://www.dropbox.com/scl/fi/yow598avxczd4xmex4bm7/GA-Release-1412.zip?rlkey=2wltkuhxnx4hvxoulkz8vq9oe&st=pu1r1mpv&dl=0

**Comment by MartinSVK12** [comment]
This is not a problem caused by vanilla BTA (your instance is modded after all) and so doesn't belong here.
