### ISSUE TITLE
Implement farmable cocoa beans

### ISSUE THREAD

**Issue by SkyDeckAGoGo** [Better-than-Adventure/bta-issues#72]
Small trees that grow in rainforest biomes. Leaves sprout cocoa beans in summer like cherry trees

**Comment by LukeisStuff** [comment]
![Cocoa Tree All textures](https://user-images.githubusercontent.com/92662759/166267856-1beca7d2-db69-48e3-bad9-8350e523e78e.png)
Potential Textures

**Comment by Tim79000** [comment]
I think this should be closed now however there is no wood associated with them yet unless this is intentional.

**Comment by Tim79000** [comment]
Ok apparently the wood color is now associated with Caatingas, so I assume this would be a good idea to close now.
